version: "3.2"
   
networks:
  calc_overlay:
    driver: overlay
    attachable: true
   
services:
  libcalculadora:
    build:
      context: .
      dockerfile: Dockerfile-depend
    image: "libcalculadora:1.0"
  web:
    build:
      context: .
      dockerfile: Dockerfile-calculadora
    image: "calculadora:${VERSAO}"
    command: "uvicorn calculadora:app --host 0.0.0.0 --port ${PORT_CALC}"
    ports:
      - "${PORT_CALC}:${PORT_CALC}"
    networks:
      - calc_overlay
    env_file:
      - .env
  soma:
    build:
      context: .
      dockerfile: Dockerfile-soma
    image: "soma:${VERSAO}"
    command: "uvicorn soma:app --host 0.0.0.0 --port ${PORT_SOMA}"
    ports:
      - "${PORT_SOMA}:${PORT_SOMA}"
    networks:
      - calc_overlay
    env_file:
      - .env
  subtracao:
    build:
      context: .
      dockerfile: Dockerfile-subtracao
    image: "subtracao:${VERSAO}"
    command: "uvicorn subtracao:app --host 0.0.0.0 --port ${PORT_SUB}"
    ports:
      - "${PORT_SUB}:${PORT_SUB}"
    networks:
      - calc_overlay
    env_file:
      - .env
  multiplicacao:
    build:
      context: .
      dockerfile: Dockerfile-multiplicacao
    image: "multiplicacao:${VERSAO}"
    command: "uvicorn multiplicacao:app --host 0.0.0.0 --port ${PORT_MULTI}"
    ports:
      - "${PORT_MULTI}:${PORT_MULTI}"
    networks:
      - calc_overlay
    env_file:
      - .env
  divisao:
    build:
      context: .
      dockerfile: Dockerfile-divisao
    image: "divisao:${VERSAO}"
    command: "uvicorn divisao:app --host 0.0.0.0 --port ${PORT_DIV}"
    ports:
      - "${PORT_DIV}:${PORT_DIV}"
    networks:
      - calc_overlay
    env_file:
      - .env
