# set base image (host OS)
FROM libcalculadora:1.0

# set the working directory in the container
WORKDIR .

EXPOSE 8200

# copy the content of the local src directory to the working directory
COPY . .

